### ISSUE TITLE
收款界面优化

### ISSUE THREAD

**Issue by edisonal** [QiMeng-Technology/CiCiPayment#39]
1、	信息提示，有时候收不到，收款界面文字显示是微信支付，还是支付宝支付
2、	收款码应提高像素，并降低疏密度，疏点。（提高扫码效率）
3、文字再大一号

**Comment by zyga501** [comment]
2、	收款码应提高像素，并降低疏密度，疏点。（提高扫码效率）
================
者不好弄的；速度也会有影响
