### ISSUE TITLE
公众号菜单调整

### ISSUE THREAD

**Issue by edisonal** [QiMeng-Technology/CiCiPayment#42]
公众号上的菜单调整为：
1、我要收款 
2、 企盟小贷（原先的贷款界面连接） 
3、个人中心 下设 子菜单如下：
 a.我要查账（现在的页面）
 b.我的信息 （修改到账银行卡号）
 c.增加收银台（一商户，多个码的问题，如何实现？）
d.关于我们  (显示一些固定公告，备用）

**Comment by zyga501** [comment]
@edisonal  企盟小贷（原先的贷款界面连接） 原先的地址是多少 项目找不到了

**Comment by zyga501** [comment]
只是菜单已经建好；

**Comment by edisonal** [comment]
http://qimpay.com/plat/goodspay/goodssign.jsp
