### ISSUE TITLE
我要查账界面，优化

### ISSUE THREAD

**Issue by edisonal** [QiMeng-Technology/CiCiPayment#44]
1、将当前显示的卡号，改为：到账卡号（到账的银行卡卡号），如：中信银行 6225******562134
2、订单金额注意，显示到元，
3、清算状态显示为   t0或t1  解释：企盟资质下全为t0.自有资质才是 t1
4、字体大一号吧。现在的可能太小了

**Comment by zyga501** [comment]
**√**1、将当前显示的卡号，改为：到账卡号（到账的银行卡卡号），如：中信银行 6225******562134
**√**2、订单金额注意，显示到元，
_?_3、清算状态显示为 t0或t1 解释：企盟资质下全为t0.自有资质才是 t1
**√**4、字体大一号吧。现在的可能太小了

**Comment by zyga501** [comment]
close
